/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget {
  'id' : bigint,
  'month' : bigint,
  'owner' : UserId,
  'limitCents' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'color' : string,
  'year' : bigint,
  'category' : string,
}
export interface BudgetInput {
  'month' : bigint,
  'limitCents' : bigint,
  'name' : string,
  'color' : string,
  'year' : bigint,
  'category' : string,
}
export interface BudgetSummary {
  'totalSpentCents' : bigint,
  'budget' : Budget,
  'remainingCents' : bigint,
}
export interface CategoryBreakdownPoint {
  'name' : string,
  'color' : string,
  'amountCents' : bigint,
  'budgetId' : string,
}
export interface CategoryTrendPoint {
  'month' : bigint,
  'limitCents' : bigint,
  'year' : bigint,
  'spentCents' : bigint,
  'budgetId' : bigint,
  'budgetName' : string,
}
export interface DailySpendingPoint { 'day' : bigint, 'amountCents' : bigint }
export interface Expense {
  'id' : bigint,
  'recurringTemplateId' : [] | [bigint],
  'receiptUrl' : [] | [string],
  'owner' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'amountCents' : bigint,
  'budgetId' : bigint,
  'notes' : [] | [string],
}
export interface ExpenseInput {
  'receiptUrl' : [] | [string],
  'date' : string,
  'amountCents' : bigint,
  'budgetId' : bigint,
  'notes' : [] | [string],
}
export interface MonthlySummary {
  'month' : bigint,
  'totalSpentCents' : bigint,
  'year' : bigint,
  'totalBudgetCents' : bigint,
  'budgets' : Array<BudgetSummary>,
}
export interface MonthlyTrendPoint {
  'month' : bigint,
  'totalSpentCents' : bigint,
  'year' : bigint,
}
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface RecurringTemplate {
  'id' : bigint,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'dayOfMonth' : bigint,
  'amountCents' : bigint,
  'budgetId' : bigint,
  'notes' : [] | [string],
}
export interface RecurringTemplateInput {
  'name' : string,
  'dayOfMonth' : bigint,
  'amountCents' : bigint,
  'budgetId' : bigint,
  'notes' : [] | [string],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserSettings { 'alertThresholdPercent' : bigint }
export interface _SERVICE {
  'applyRecurringTemplates' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'createBudget' : ActorMethod<[BudgetInput], Budget>,
  'createExpense' : ActorMethod<[ExpenseInput], Expense>,
  'createNote' : ActorMethod<[string, string], Note>,
  'createRecurringTemplate' : ActorMethod<
    [RecurringTemplateInput],
    RecurringTemplate
  >,
  'deleteBudget' : ActorMethod<[bigint], boolean>,
  'deleteExpense' : ActorMethod<[bigint], boolean>,
  'deleteNote' : ActorMethod<[string], boolean>,
  'deleteRecurringTemplate' : ActorMethod<[bigint], boolean>,
  'getBudget' : ActorMethod<[bigint], [] | [Budget]>,
  'getCategoryBreakdown' : ActorMethod<
    [bigint, bigint],
    Array<CategoryBreakdownPoint>
  >,
  'getCategoryBreakdownForRange' : ActorMethod<
    [string, string],
    Array<CategoryBreakdownPoint>
  >,
  'getCategoryTrend' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    Array<CategoryTrendPoint>
  >,
  'getDailySpending' : ActorMethod<[bigint, bigint], Array<DailySpendingPoint>>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getExpensesInRange' : ActorMethod<[string, string], Array<Expense>>,
  'getMonthlySummary' : ActorMethod<[bigint, bigint], MonthlySummary>,
  'getMonthlyTrend' : ActorMethod<
    [bigint, bigint, bigint],
    Array<MonthlyTrendPoint>
  >,
  'getRecurringTemplate' : ActorMethod<[bigint], [] | [RecurringTemplate]>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'listBudgets' : ActorMethod<[bigint, bigint], Array<Budget>>,
  'listExpenses' : ActorMethod<[bigint], Array<Expense>>,
  'listNotes' : ActorMethod<[], Array<Note>>,
  'listRecurringTemplates' : ActorMethod<[bigint], Array<RecurringTemplate>>,
  'searchExpenses' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Expense>
  >,
  'updateBudget' : ActorMethod<[bigint, BudgetInput], [] | [Budget]>,
  'updateExpense' : ActorMethod<[bigint, ExpenseInput], [] | [Expense]>,
  'updateNote' : ActorMethod<[string, string, string], [] | [Note]>,
  'updateRecurringTemplate' : ActorMethod<
    [bigint, RecurringTemplateInput],
    [] | [RecurringTemplate]
  >,
  'updateUserSettings' : ActorMethod<[UserSettings], UserSettings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];