/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Budget = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'owner' : UserId,
  'limitCents' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'category' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'recurringTemplateId' : IDL.Opt(IDL.Nat),
  'receiptUrl' : IDL.Opt(IDL.Text),
  'owner' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const BillPaymentInput = IDL.Record({
  'month' : IDL.Nat,
  'recurringTemplateId' : IDL.Text,
  'year' : IDL.Nat,
  'paidDate' : IDL.Opt(Timestamp),
  'paidAmountCents' : IDL.Opt(IDL.Nat),
  'dueDay' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const BillPayment = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Nat,
  'recurringTemplateId' : IDL.Text,
  'owner' : UserId,
  'year' : IDL.Nat,
  'paidDate' : IDL.Opt(Timestamp),
  'paidAmountCents' : IDL.Opt(IDL.Nat),
  'dueDay' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const BudgetInput = IDL.Record({
  'month' : IDL.Nat,
  'limitCents' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'category' : IDL.Text,
});
export const BudgetTemplateCategory = IDL.Record({
  'limitCents' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'category' : IDL.Text,
});
export const BudgetTemplateInput = IDL.Record({
  'categories' : IDL.Vec(BudgetTemplateCategory),
  'name' : IDL.Text,
});
export const BudgetTemplate = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(BudgetTemplateCategory),
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const ExpenseInput = IDL.Record({
  'receiptUrl' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const RecurringTemplateInput = IDL.Record({
  'name' : IDL.Text,
  'dayOfMonth' : IDL.Nat,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const RecurringTemplate = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'dayOfMonth' : IDL.Nat,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const CategoryBreakdownPoint = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'amountCents' : IDL.Int,
  'budgetId' : IDL.Text,
});
export const CategoryTrendPoint = IDL.Record({
  'month' : IDL.Nat,
  'limitCents' : IDL.Nat,
  'year' : IDL.Nat,
  'spentCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'budgetName' : IDL.Text,
});
export const DailySpendingPoint = IDL.Record({
  'day' : IDL.Nat,
  'amountCents' : IDL.Int,
});
export const BudgetSummary = IDL.Record({
  'totalSpentCents' : IDL.Nat,
  'budget' : Budget,
  'remainingCents' : IDL.Int,
});
export const MonthlySummary = IDL.Record({
  'month' : IDL.Nat,
  'totalSpentCents' : IDL.Nat,
  'year' : IDL.Nat,
  'totalBudgetCents' : IDL.Nat,
  'budgets' : IDL.Vec(BudgetSummary),
});
export const MonthlyTrendPoint = IDL.Record({
  'month' : IDL.Nat,
  'totalSpentCents' : IDL.Nat,
  'year' : IDL.Nat,
});
export const UserSettings = IDL.Record({ 'alertThresholdPercent' : IDL.Nat });

export const idlService = IDL.Service({
  'applyBudgetTemplate' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Budget)],
      [],
    ),
  'applyRecurringTemplates' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      [],
    ),
  'createBillPayment' : IDL.Func([BillPaymentInput], [BillPayment], []),
  'createBudget' : IDL.Func([BudgetInput], [Budget], []),
  'createBudgetTemplate' : IDL.Func(
      [BudgetTemplateInput],
      [BudgetTemplate],
      [],
    ),
  'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [Note], []),
  'createRecurringTemplate' : IDL.Func(
      [RecurringTemplateInput],
      [RecurringTemplate],
      [],
    ),
  'deleteBillPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBudget' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteBudgetTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteRecurringTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBillPayment' : IDL.Func([IDL.Text], [IDL.Opt(BillPayment)], ['query']),
  'getBudget' : IDL.Func([IDL.Nat], [IDL.Opt(Budget)], ['query']),
  'getBudgetTemplate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BudgetTemplate)],
      ['query'],
    ),
  'getCategoryBreakdown' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryBreakdownPoint)],
      ['query'],
    ),
  'getCategoryBreakdownForRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CategoryBreakdownPoint)],
      ['query'],
    ),
  'getCategoryTrend' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryTrendPoint)],
      ['query'],
    ),
  'getDailySpending' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DailySpendingPoint)],
      ['query'],
    ),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getExpensesInRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getMonthlySummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlySummary],
      ['query'],
    ),
  'getMonthlyTrend' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(MonthlyTrendPoint)],
      ['query'],
    ),
  'getRecurringTemplate' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RecurringTemplate)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'listBillPayments' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BillPayment)],
      ['query'],
    ),
  'listBudgetTemplates' : IDL.Func([], [IDL.Vec(BudgetTemplate)], ['query']),
  'listBudgets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Budget)], ['query']),
  'listExpenses' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
  'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'listRecurringTemplates' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RecurringTemplate)],
      ['query'],
    ),
  'searchExpenses' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'updateBillPayment' : IDL.Func(
      [IDL.Text, BillPaymentInput],
      [IDL.Opt(BillPayment)],
      [],
    ),
  'updateBudget' : IDL.Func([IDL.Nat, BudgetInput], [IDL.Opt(Budget)], []),
  'updateBudgetTemplate' : IDL.Func(
      [IDL.Text, BudgetTemplateInput],
      [IDL.Opt(BudgetTemplate)],
      [],
    ),
  'updateExpense' : IDL.Func([IDL.Nat, ExpenseInput], [IDL.Opt(Expense)], []),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(Note)], []),
  'updateRecurringTemplate' : IDL.Func(
      [IDL.Nat, RecurringTemplateInput],
      [IDL.Opt(RecurringTemplate)],
      [],
    ),
  'updateUserSettings' : IDL.Func([UserSettings], [UserSettings], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Budget = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'owner' : UserId,
    'limitCents' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'recurringTemplateId' : IDL.Opt(IDL.Nat),
    'receiptUrl' : IDL.Opt(IDL.Text),
    'owner' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const BillPaymentInput = IDL.Record({
    'month' : IDL.Nat,
    'recurringTemplateId' : IDL.Text,
    'year' : IDL.Nat,
    'paidDate' : IDL.Opt(Timestamp),
    'paidAmountCents' : IDL.Opt(IDL.Nat),
    'dueDay' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const BillPayment = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Nat,
    'recurringTemplateId' : IDL.Text,
    'owner' : UserId,
    'year' : IDL.Nat,
    'paidDate' : IDL.Opt(Timestamp),
    'paidAmountCents' : IDL.Opt(IDL.Nat),
    'dueDay' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const BudgetInput = IDL.Record({
    'month' : IDL.Nat,
    'limitCents' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'category' : IDL.Text,
  });
  const BudgetTemplateCategory = IDL.Record({
    'limitCents' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'category' : IDL.Text,
  });
  const BudgetTemplateInput = IDL.Record({
    'categories' : IDL.Vec(BudgetTemplateCategory),
    'name' : IDL.Text,
  });
  const BudgetTemplate = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(BudgetTemplateCategory),
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const ExpenseInput = IDL.Record({
    'receiptUrl' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const RecurringTemplateInput = IDL.Record({
    'name' : IDL.Text,
    'dayOfMonth' : IDL.Nat,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const RecurringTemplate = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'dayOfMonth' : IDL.Nat,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const CategoryBreakdownPoint = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'amountCents' : IDL.Int,
    'budgetId' : IDL.Text,
  });
  const CategoryTrendPoint = IDL.Record({
    'month' : IDL.Nat,
    'limitCents' : IDL.Nat,
    'year' : IDL.Nat,
    'spentCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'budgetName' : IDL.Text,
  });
  const DailySpendingPoint = IDL.Record({
    'day' : IDL.Nat,
    'amountCents' : IDL.Int,
  });
  const BudgetSummary = IDL.Record({
    'totalSpentCents' : IDL.Nat,
    'budget' : Budget,
    'remainingCents' : IDL.Int,
  });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Nat,
    'totalSpentCents' : IDL.Nat,
    'year' : IDL.Nat,
    'totalBudgetCents' : IDL.Nat,
    'budgets' : IDL.Vec(BudgetSummary),
  });
  const MonthlyTrendPoint = IDL.Record({
    'month' : IDL.Nat,
    'totalSpentCents' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const UserSettings = IDL.Record({ 'alertThresholdPercent' : IDL.Nat });
  
  return IDL.Service({
    'applyBudgetTemplate' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Budget)],
        [],
      ),
    'applyRecurringTemplates' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        [],
      ),
    'createBillPayment' : IDL.Func([BillPaymentInput], [BillPayment], []),
    'createBudget' : IDL.Func([BudgetInput], [Budget], []),
    'createBudgetTemplate' : IDL.Func(
        [BudgetTemplateInput],
        [BudgetTemplate],
        [],
      ),
    'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [Note], []),
    'createRecurringTemplate' : IDL.Func(
        [RecurringTemplateInput],
        [RecurringTemplate],
        [],
      ),
    'deleteBillPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBudget' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteBudgetTemplate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNote' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteRecurringTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBillPayment' : IDL.Func([IDL.Text], [IDL.Opt(BillPayment)], ['query']),
    'getBudget' : IDL.Func([IDL.Nat], [IDL.Opt(Budget)], ['query']),
    'getBudgetTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BudgetTemplate)],
        ['query'],
      ),
    'getCategoryBreakdown' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryBreakdownPoint)],
        ['query'],
      ),
    'getCategoryBreakdownForRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CategoryBreakdownPoint)],
        ['query'],
      ),
    'getCategoryTrend' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryTrendPoint)],
        ['query'],
      ),
    'getDailySpending' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DailySpendingPoint)],
        ['query'],
      ),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getExpensesInRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getMonthlySummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlySummary],
        ['query'],
      ),
    'getMonthlyTrend' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(MonthlyTrendPoint)],
        ['query'],
      ),
    'getRecurringTemplate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RecurringTemplate)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'listBillPayments' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BillPayment)],
        ['query'],
      ),
    'listBudgetTemplates' : IDL.Func([], [IDL.Vec(BudgetTemplate)], ['query']),
    'listBudgets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Budget)], ['query']),
    'listExpenses' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'listRecurringTemplates' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RecurringTemplate)],
        ['query'],
      ),
    'searchExpenses' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'updateBillPayment' : IDL.Func(
        [IDL.Text, BillPaymentInput],
        [IDL.Opt(BillPayment)],
        [],
      ),
    'updateBudget' : IDL.Func([IDL.Nat, BudgetInput], [IDL.Opt(Budget)], []),
    'updateBudgetTemplate' : IDL.Func(
        [IDL.Text, BudgetTemplateInput],
        [IDL.Opt(BudgetTemplate)],
        [],
      ),
    'updateExpense' : IDL.Func([IDL.Nat, ExpenseInput], [IDL.Opt(Expense)], []),
    'updateNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Note)],
        [],
      ),
    'updateRecurringTemplate' : IDL.Func(
        [IDL.Nat, RecurringTemplateInput],
        [IDL.Opt(RecurringTemplate)],
        [],
      ),
    'updateUserSettings' : IDL.Func([UserSettings], [UserSettings], []),
  });
};

export const init = ({ IDL }) => { return []; };