/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'recurringTemplateId' : IDL.Opt(IDL.Nat),
  'owner' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const BudgetInput = IDL.Record({
  'month' : IDL.Nat,
  'limitCents' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'category' : IDL.Text,
});
export const Budget = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'owner' : UserId,
  'limitCents' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'category' : IDL.Text,
});
export const ExpenseInput = IDL.Record({
  'date' : IDL.Text,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const RecurringTemplateInput = IDL.Record({
  'name' : IDL.Text,
  'dayOfMonth' : IDL.Nat,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const RecurringTemplate = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'dayOfMonth' : IDL.Nat,
  'amountCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const CategoryTrendPoint = IDL.Record({
  'month' : IDL.Nat,
  'limitCents' : IDL.Nat,
  'year' : IDL.Nat,
  'spentCents' : IDL.Nat,
  'budgetId' : IDL.Nat,
  'budgetName' : IDL.Text,
});
export const BudgetSummary = IDL.Record({
  'totalSpentCents' : IDL.Nat,
  'budget' : Budget,
  'remainingCents' : IDL.Int,
});
export const MonthlySummary = IDL.Record({
  'month' : IDL.Nat,
  'totalSpentCents' : IDL.Nat,
  'year' : IDL.Nat,
  'totalBudgetCents' : IDL.Nat,
  'budgets' : IDL.Vec(BudgetSummary),
});
export const MonthlyTrendPoint = IDL.Record({
  'month' : IDL.Nat,
  'totalSpentCents' : IDL.Nat,
  'year' : IDL.Nat,
});

export const idlService = IDL.Service({
  'applyRecurringTemplates' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      [],
    ),
  'createBudget' : IDL.Func([BudgetInput], [Budget], []),
  'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
  'createRecurringTemplate' : IDL.Func(
      [RecurringTemplateInput],
      [RecurringTemplate],
      [],
    ),
  'deleteBudget' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteRecurringTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBudget' : IDL.Func([IDL.Nat], [IDL.Opt(Budget)], ['query']),
  'getCategoryTrend' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryTrendPoint)],
      ['query'],
    ),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getMonthlySummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlySummary],
      ['query'],
    ),
  'getMonthlyTrend' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(MonthlyTrendPoint)],
      ['query'],
    ),
  'getRecurringTemplate' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RecurringTemplate)],
      ['query'],
    ),
  'listBudgets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Budget)], ['query']),
  'listExpenses' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
  'listRecurringTemplates' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RecurringTemplate)],
      ['query'],
    ),
  'updateBudget' : IDL.Func([IDL.Nat, BudgetInput], [IDL.Opt(Budget)], []),
  'updateExpense' : IDL.Func([IDL.Nat, ExpenseInput], [IDL.Opt(Expense)], []),
  'updateRecurringTemplate' : IDL.Func(
      [IDL.Nat, RecurringTemplateInput],
      [IDL.Opt(RecurringTemplate)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'recurringTemplateId' : IDL.Opt(IDL.Nat),
    'owner' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const BudgetInput = IDL.Record({
    'month' : IDL.Nat,
    'limitCents' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Budget = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'owner' : UserId,
    'limitCents' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ExpenseInput = IDL.Record({
    'date' : IDL.Text,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const RecurringTemplateInput = IDL.Record({
    'name' : IDL.Text,
    'dayOfMonth' : IDL.Nat,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const RecurringTemplate = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'dayOfMonth' : IDL.Nat,
    'amountCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const CategoryTrendPoint = IDL.Record({
    'month' : IDL.Nat,
    'limitCents' : IDL.Nat,
    'year' : IDL.Nat,
    'spentCents' : IDL.Nat,
    'budgetId' : IDL.Nat,
    'budgetName' : IDL.Text,
  });
  const BudgetSummary = IDL.Record({
    'totalSpentCents' : IDL.Nat,
    'budget' : Budget,
    'remainingCents' : IDL.Int,
  });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Nat,
    'totalSpentCents' : IDL.Nat,
    'year' : IDL.Nat,
    'totalBudgetCents' : IDL.Nat,
    'budgets' : IDL.Vec(BudgetSummary),
  });
  const MonthlyTrendPoint = IDL.Record({
    'month' : IDL.Nat,
    'totalSpentCents' : IDL.Nat,
    'year' : IDL.Nat,
  });
  
  return IDL.Service({
    'applyRecurringTemplates' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        [],
      ),
    'createBudget' : IDL.Func([BudgetInput], [Budget], []),
    'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
    'createRecurringTemplate' : IDL.Func(
        [RecurringTemplateInput],
        [RecurringTemplate],
        [],
      ),
    'deleteBudget' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteRecurringTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBudget' : IDL.Func([IDL.Nat], [IDL.Opt(Budget)], ['query']),
    'getCategoryTrend' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryTrendPoint)],
        ['query'],
      ),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getMonthlySummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlySummary],
        ['query'],
      ),
    'getMonthlyTrend' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(MonthlyTrendPoint)],
        ['query'],
      ),
    'getRecurringTemplate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RecurringTemplate)],
        ['query'],
      ),
    'listBudgets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Budget)], ['query']),
    'listExpenses' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
    'listRecurringTemplates' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RecurringTemplate)],
        ['query'],
      ),
    'updateBudget' : IDL.Func([IDL.Nat, BudgetInput], [IDL.Opt(Budget)], []),
    'updateExpense' : IDL.Func([IDL.Nat, ExpenseInput], [IDL.Opt(Expense)], []),
    'updateRecurringTemplate' : IDL.Func(
        [IDL.Nat, RecurringTemplateInput],
        [IDL.Opt(RecurringTemplate)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };