/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Budget {
    id: bigint;
    month: bigint;
    owner: UserId;
    limitCents: bigint;
    name: string;
    createdAt: Timestamp;
    color: string;
    year: bigint;
    category: string;
}
export type Timestamp = bigint;
export interface BudgetTemplateCategory {
    limitCents: bigint;
    name: string;
    color: string;
    category: string;
}
export interface MonthlyTrendPoint {
    month: bigint;
    totalSpentCents: bigint;
    year: bigint;
}
export interface BudgetTemplateInput {
    categories: Array<BudgetTemplateCategory>;
    name: string;
}
export interface CategoryBreakdownPoint {
    name: string;
    color: string;
    amountCents: bigint;
    budgetId: string;
}
export interface MonthlySummary {
    month: bigint;
    totalSpentCents: bigint;
    year: bigint;
    totalBudgetCents: bigint;
    budgets: Array<BudgetSummary>;
}
export interface Expense {
    id: bigint;
    recurringTemplateId?: bigint;
    receiptUrl?: string;
    owner: UserId;
    date: string;
    createdAt: Timestamp;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export type UserId = Principal;
export interface RecurringTemplateInput {
    name: string;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface DailySpendingPoint {
    day: bigint;
    amountCents: bigint;
}
export interface RecurringTemplate {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface CategoryTrendPoint {
    month: bigint;
    limitCents: bigint;
    year: bigint;
    spentCents: bigint;
    budgetId: bigint;
    budgetName: string;
}
export interface BudgetSummary {
    totalSpentCents: bigint;
    budget: Budget;
    remainingCents: bigint;
}
export interface BillPaymentInput {
    month: bigint;
    recurringTemplateId: string;
    year: bigint;
    paidDate?: Timestamp;
    paidAmountCents?: bigint;
    dueDay: bigint;
    notes?: string;
}
export interface BillPayment {
    id: string;
    month: bigint;
    recurringTemplateId: string;
    owner: UserId;
    year: bigint;
    paidDate?: Timestamp;
    paidAmountCents?: bigint;
    dueDay: bigint;
    notes?: string;
}
export interface UserSettings {
    alertThresholdPercent: bigint;
}
export interface ExpenseInput {
    receiptUrl?: string;
    date: string;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface BudgetInput {
    month: bigint;
    limitCents: bigint;
    name: string;
    color: string;
    year: bigint;
    category: string;
}
export interface BudgetTemplate {
    id: string;
    categories: Array<BudgetTemplateCategory>;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
}
export interface Note {
    id: string;
    title: string;
    content: string;
    userId: Principal;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface backendInterface {
    applyBudgetTemplate(templateId: string, year: bigint, month: bigint): Promise<Array<Budget>>;
    applyRecurringTemplates(year: bigint, month: bigint): Promise<Array<Expense>>;
    createBillPayment(input: BillPaymentInput): Promise<BillPayment>;
    createBudget(input: BudgetInput): Promise<Budget>;
    createBudgetTemplate(input: BudgetTemplateInput): Promise<BudgetTemplate>;
    createExpense(input: ExpenseInput): Promise<Expense>;
    createNote(title: string, content: string): Promise<Note>;
    createRecurringTemplate(input: RecurringTemplateInput): Promise<RecurringTemplate>;
    deleteBillPayment(id: string): Promise<boolean>;
    deleteBudget(id: bigint): Promise<boolean>;
    deleteBudgetTemplate(id: string): Promise<boolean>;
    deleteExpense(id: bigint): Promise<boolean>;
    deleteNote(id: string): Promise<boolean>;
    deleteRecurringTemplate(id: bigint): Promise<boolean>;
    getBillPayment(id: string): Promise<BillPayment | null>;
    getBudget(id: bigint): Promise<Budget | null>;
    getBudgetTemplate(id: string): Promise<BudgetTemplate | null>;
    getCategoryBreakdown(year: bigint, month: bigint): Promise<Array<CategoryBreakdownPoint>>;
    getCategoryBreakdownForRange(startDate: string, endDate: string): Promise<Array<CategoryBreakdownPoint>>;
    getCategoryTrend(budgetId: bigint, months: bigint, currentYear: bigint, currentMonth: bigint): Promise<Array<CategoryTrendPoint>>;
    getDailySpending(year: bigint, month: bigint): Promise<Array<DailySpendingPoint>>;
    getExpense(id: bigint): Promise<Expense | null>;
    getExpensesInRange(startDate: string, endDate: string): Promise<Array<Expense>>;
    getMonthlySummary(year: bigint, month: bigint): Promise<MonthlySummary>;
    getMonthlyTrend(months: bigint, currentYear: bigint, currentMonth: bigint): Promise<Array<MonthlyTrendPoint>>;
    getRecurringTemplate(id: bigint): Promise<RecurringTemplate | null>;
    getUserSettings(): Promise<UserSettings>;
    listBillPayments(year: bigint, month: bigint): Promise<Array<BillPayment>>;
    listBudgetTemplates(): Promise<Array<BudgetTemplate>>;
    listBudgets(year: bigint, month: bigint): Promise<Array<Budget>>;
    listExpenses(budgetId: bigint): Promise<Array<Expense>>;
    listNotes(): Promise<Array<Note>>;
    listRecurringTemplates(budgetId: bigint): Promise<Array<RecurringTemplate>>;
    searchExpenses(startDate: string, endDate: string, queryText: string | null, categoryId: bigint | null, minAmountCents: bigint | null, maxAmountCents: bigint | null): Promise<Array<Expense>>;
    updateBillPayment(id: string, input: BillPaymentInput): Promise<BillPayment | null>;
    updateBudget(id: bigint, input: BudgetInput): Promise<Budget | null>;
    updateBudgetTemplate(id: string, input: BudgetTemplateInput): Promise<BudgetTemplate | null>;
    updateExpense(id: bigint, input: ExpenseInput): Promise<Expense | null>;
    updateNote(id: string, title: string, content: string): Promise<Note | null>;
    updateRecurringTemplate(id: bigint, input: RecurringTemplateInput): Promise<RecurringTemplate | null>;
    updateUserSettings(settings: UserSettings): Promise<UserSettings>;
}
import type { BillPayment as _BillPayment, BillPaymentInput as _BillPaymentInput, Budget as _Budget, BudgetTemplate as _BudgetTemplate, Expense as _Expense, ExpenseInput as _ExpenseInput, Note as _Note, RecurringTemplate as _RecurringTemplate, RecurringTemplateInput as _RecurringTemplateInput, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyBudgetTemplate(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.applyBudgetTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyBudgetTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async applyRecurringTemplates(arg0: bigint, arg1: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.applyRecurringTemplates(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyRecurringTemplates(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBillPayment(arg0: BillPaymentInput): Promise<BillPayment> {
        if (this.processError) {
            try {
                const result = await this.actor.createBillPayment(to_candid_BillPaymentInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BillPayment_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBillPayment(to_candid_BillPaymentInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BillPayment_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBudget(arg0: BudgetInput): Promise<Budget> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudget(arg0);
            return result;
        }
    }
    async createBudgetTemplate(arg0: BudgetTemplateInput): Promise<BudgetTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudgetTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudgetTemplate(arg0);
            return result;
        }
    }
    async createExpense(arg0: ExpenseInput): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(to_candid_ExpenseInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Expense_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(to_candid_ExpenseInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Expense_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: string, arg1: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1);
            return result;
        }
    }
    async createRecurringTemplate(arg0: RecurringTemplateInput): Promise<RecurringTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecurringTemplate(to_candid_RecurringTemplateInput_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RecurringTemplate_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecurringTemplate(to_candid_RecurringTemplateInput_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RecurringTemplate_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBillPayment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBillPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBillPayment(arg0);
            return result;
        }
    }
    async deleteBudget(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudget(arg0);
            return result;
        }
    }
    async deleteBudgetTemplate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetTemplate(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteRecurringTemplate(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecurringTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecurringTemplate(arg0);
            return result;
        }
    }
    async getBillPayment(arg0: string): Promise<BillPayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillPayment(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillPayment(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudget(arg0: bigint): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetTemplate(arg0: string): Promise<BudgetTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetTemplate(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetTemplate(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryBreakdown(arg0: bigint, arg1: bigint): Promise<Array<CategoryBreakdownPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryBreakdown(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryBreakdown(arg0, arg1);
            return result;
        }
    }
    async getCategoryBreakdownForRange(arg0: string, arg1: string): Promise<Array<CategoryBreakdownPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryBreakdownForRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryBreakdownForRange(arg0, arg1);
            return result;
        }
    }
    async getCategoryTrend(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<Array<CategoryTrendPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryTrend(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryTrend(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getDailySpending(arg0: bigint, arg1: bigint): Promise<Array<DailySpendingPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySpending(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySpending(arg0, arg1);
            return result;
        }
    }
    async getExpense(arg0: bigint): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesInRange(arg0: string, arg1: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesInRange(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesInRange(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySummary(arg0: bigint, arg1: bigint): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0, arg1);
            return result;
        }
    }
    async getMonthlyTrend(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<MonthlyTrendPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyTrend(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyTrend(arg0, arg1, arg2);
            return result;
        }
    }
    async getRecurringTemplate(arg0: bigint): Promise<RecurringTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecurringTemplate(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecurringTemplate(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return result;
        }
    }
    async listBillPayments(arg0: bigint, arg1: bigint): Promise<Array<BillPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBillPayments(arg0, arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBillPayments(arg0, arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBudgetTemplates(): Promise<Array<BudgetTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBudgetTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBudgetTemplates();
            return result;
        }
    }
    async listBudgets(arg0: bigint, arg1: bigint): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBudgets(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBudgets(arg0, arg1);
            return result;
        }
    }
    async listExpenses(arg0: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotes();
            return result;
        }
    }
    async listRecurringTemplates(arg0: bigint): Promise<Array<RecurringTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecurringTemplates(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecurringTemplates(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchExpenses(arg0: string, arg1: string, arg2: string | null, arg3: bigint | null, arg4: bigint | null, arg5: bigint | null): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchExpenses(arg0, arg1, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchExpenses(arg0, arg1, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBillPayment(arg0: string, arg1: BillPaymentInput): Promise<BillPayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBillPayment(arg0, to_candid_BillPaymentInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBillPayment(arg0, to_candid_BillPaymentInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBudget(arg0: bigint, arg1: BudgetInput): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudget(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudget(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBudgetTemplate(arg0: string, arg1: BudgetTemplateInput): Promise<BudgetTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetTemplate(arg0, arg1);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetTemplate(arg0, arg1);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateExpense(arg0: bigint, arg1: ExpenseInput): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, to_candid_ExpenseInput_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, to_candid_ExpenseInput_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: string, arg1: string, arg2: string): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecurringTemplate(arg0: bigint, arg1: RecurringTemplateInput): Promise<RecurringTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecurringTemplate(arg0, to_candid_RecurringTemplateInput_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecurringTemplate(arg0, to_candid_RecurringTemplateInput_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserSettings(arg0: UserSettings): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0);
            return result;
        }
    }
}
function from_candid_BillPayment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillPayment): BillPayment {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringTemplate_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringTemplate): RecurringTemplate {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillPayment]): BillPayment | null {
    return value.length === 0 ? null : from_candid_BillPayment_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Budget]): Budget | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BudgetTemplate]): BudgetTemplate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expense]): Expense | null {
    return value.length === 0 ? null : from_candid_Expense_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecurringTemplate]): RecurringTemplate | null {
    return value.length === 0 ? null : from_candid_RecurringTemplate_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
}): {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        dayOfMonth: value.dayOfMonth,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    recurringTemplateId: [] | [bigint];
    receiptUrl: [] | [string];
    owner: _UserId;
    date: string;
    createdAt: _Timestamp;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
}): {
    id: bigint;
    recurringTemplateId?: bigint;
    receiptUrl?: string;
    owner: UserId;
    date: string;
    createdAt: Timestamp;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
} {
    return {
        id: value.id,
        recurringTemplateId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.recurringTemplateId)),
        receiptUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.receiptUrl)),
        owner: value.owner,
        date: value.date,
        createdAt: value.createdAt,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    month: bigint;
    recurringTemplateId: string;
    owner: _UserId;
    year: bigint;
    paidDate: [] | [_Timestamp];
    paidAmountCents: [] | [bigint];
    dueDay: bigint;
    notes: [] | [string];
}): {
    id: string;
    month: bigint;
    recurringTemplateId: string;
    owner: UserId;
    year: bigint;
    paidDate?: Timestamp;
    paidAmountCents?: bigint;
    dueDay: bigint;
    notes?: string;
} {
    return {
        id: value.id,
        month: value.month,
        recurringTemplateId: value.recurringTemplateId,
        owner: value.owner,
        year: value.year,
        paidDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.paidDate)),
        paidAmountCents: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.paidAmountCents)),
        dueDay: value.dueDay,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillPayment>): Array<BillPayment> {
    return value.map((x)=>from_candid_BillPayment_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecurringTemplate>): Array<RecurringTemplate> {
    return value.map((x)=>from_candid_RecurringTemplate_n15(_uploadFile, _downloadFile, x));
}
function to_candid_BillPaymentInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillPaymentInput): _BillPaymentInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseInput): _ExpenseInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringTemplateInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringTemplateInput): _RecurringTemplateInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receiptUrl?: string;
    date: string;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}): {
    receiptUrl: [] | [string];
    date: string;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
} {
    return {
        receiptUrl: value.receiptUrl ? candid_some(value.receiptUrl) : candid_none(),
        date: value.date,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}): {
    name: string;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
} {
    return {
        name: value.name,
        dayOfMonth: value.dayOfMonth,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: bigint;
    recurringTemplateId: string;
    year: bigint;
    paidDate?: Timestamp;
    paidAmountCents?: bigint;
    dueDay: bigint;
    notes?: string;
}): {
    month: bigint;
    recurringTemplateId: string;
    year: bigint;
    paidDate: [] | [_Timestamp];
    paidAmountCents: [] | [bigint];
    dueDay: bigint;
    notes: [] | [string];
} {
    return {
        month: value.month,
        recurringTemplateId: value.recurringTemplateId,
        year: value.year,
        paidDate: value.paidDate ? candid_some(value.paidDate) : candid_none(),
        paidAmountCents: value.paidAmountCents ? candid_some(value.paidAmountCents) : candid_none(),
        dueDay: value.dueDay,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
