/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface RecurringTemplateInput {
    name: string;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface RecurringTemplate {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface CategoryTrendPoint {
    month: bigint;
    limitCents: bigint;
    year: bigint;
    spentCents: bigint;
    budgetId: bigint;
    budgetName: string;
}
export interface MonthlyTrendPoint {
    month: bigint;
    totalSpentCents: bigint;
    year: bigint;
}
export interface BudgetSummary {
    totalSpentCents: bigint;
    budget: Budget;
    remainingCents: bigint;
}
export interface MonthlySummary {
    month: bigint;
    totalSpentCents: bigint;
    year: bigint;
    totalBudgetCents: bigint;
    budgets: Array<BudgetSummary>;
}
export interface ExpenseInput {
    receiptUrl?: string;
    date: string;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface Expense {
    id: bigint;
    recurringTemplateId?: bigint;
    receiptUrl?: string;
    owner: UserId;
    date: string;
    createdAt: Timestamp;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}
export interface BudgetInput {
    month: bigint;
    limitCents: bigint;
    name: string;
    color: string;
    year: bigint;
    category: string;
}
export interface Budget {
    id: bigint;
    month: bigint;
    owner: UserId;
    limitCents: bigint;
    name: string;
    createdAt: Timestamp;
    color: string;
    year: bigint;
    category: string;
}
export interface backendInterface {
    applyRecurringTemplates(year: bigint, month: bigint): Promise<Array<Expense>>;
    createBudget(input: BudgetInput): Promise<Budget>;
    createExpense(input: ExpenseInput): Promise<Expense>;
    createRecurringTemplate(input: RecurringTemplateInput): Promise<RecurringTemplate>;
    deleteBudget(id: bigint): Promise<boolean>;
    deleteExpense(id: bigint): Promise<boolean>;
    deleteRecurringTemplate(id: bigint): Promise<boolean>;
    getBudget(id: bigint): Promise<Budget | null>;
    getCategoryTrend(budgetId: bigint, months: bigint, currentYear: bigint, currentMonth: bigint): Promise<Array<CategoryTrendPoint>>;
    getExpense(id: bigint): Promise<Expense | null>;
    getMonthlySummary(year: bigint, month: bigint): Promise<MonthlySummary>;
    getMonthlyTrend(months: bigint, currentYear: bigint, currentMonth: bigint): Promise<Array<MonthlyTrendPoint>>;
    getRecurringTemplate(id: bigint): Promise<RecurringTemplate | null>;
    listBudgets(year: bigint, month: bigint): Promise<Array<Budget>>;
    listExpenses(budgetId: bigint): Promise<Array<Expense>>;
    listRecurringTemplates(budgetId: bigint): Promise<Array<RecurringTemplate>>;
    updateBudget(id: bigint, input: BudgetInput): Promise<Budget | null>;
    updateExpense(id: bigint, input: ExpenseInput): Promise<Expense | null>;
    updateRecurringTemplate(id: bigint, input: RecurringTemplateInput): Promise<RecurringTemplate | null>;
}
import type { Budget as _Budget, Expense as _Expense, ExpenseInput as _ExpenseInput, RecurringTemplate as _RecurringTemplate, RecurringTemplateInput as _RecurringTemplateInput, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyRecurringTemplates(arg0: bigint, arg1: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.applyRecurringTemplates(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyRecurringTemplates(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBudget(arg0: BudgetInput): Promise<Budget> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudget(arg0);
            return result;
        }
    }
    async createExpense(arg0: ExpenseInput): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(to_candid_ExpenseInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Expense_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(to_candid_ExpenseInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Expense_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecurringTemplate(arg0: RecurringTemplateInput): Promise<RecurringTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecurringTemplate(to_candid_RecurringTemplateInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RecurringTemplate_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecurringTemplate(to_candid_RecurringTemplateInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RecurringTemplate_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBudget(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudget(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteRecurringTemplate(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecurringTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecurringTemplate(arg0);
            return result;
        }
    }
    async getBudget(arg0: bigint): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryTrend(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<Array<CategoryTrendPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryTrend(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryTrend(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getExpense(arg0: bigint): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySummary(arg0: bigint, arg1: bigint): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0, arg1);
            return result;
        }
    }
    async getMonthlyTrend(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<MonthlyTrendPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyTrend(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyTrend(arg0, arg1, arg2);
            return result;
        }
    }
    async getRecurringTemplate(arg0: bigint): Promise<RecurringTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecurringTemplate(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecurringTemplate(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBudgets(arg0: bigint, arg1: bigint): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBudgets(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBudgets(arg0, arg1);
            return result;
        }
    }
    async listExpenses(arg0: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecurringTemplates(arg0: bigint): Promise<Array<RecurringTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecurringTemplates(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecurringTemplates(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBudget(arg0: bigint, arg1: BudgetInput): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudget(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudget(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateExpense(arg0: bigint, arg1: ExpenseInput): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, to_candid_ExpenseInput_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, to_candid_ExpenseInput_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecurringTemplate(arg0: bigint, arg1: RecurringTemplateInput): Promise<RecurringTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecurringTemplate(arg0, to_candid_RecurringTemplateInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecurringTemplate(arg0, to_candid_RecurringTemplateInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Expense_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringTemplate_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringTemplate): RecurringTemplate {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Budget]): Budget | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expense]): Expense | null {
    return value.length === 0 ? null : from_candid_Expense_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecurringTemplate]): RecurringTemplate | null {
    return value.length === 0 ? null : from_candid_RecurringTemplate_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
}): {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        dayOfMonth: value.dayOfMonth,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    recurringTemplateId: [] | [bigint];
    receiptUrl: [] | [string];
    owner: _UserId;
    date: string;
    createdAt: _Timestamp;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
}): {
    id: bigint;
    recurringTemplateId?: bigint;
    receiptUrl?: string;
    owner: UserId;
    date: string;
    createdAt: Timestamp;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
} {
    return {
        id: value.id,
        recurringTemplateId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.recurringTemplateId)),
        receiptUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.receiptUrl)),
        owner: value.owner,
        date: value.date,
        createdAt: value.createdAt,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecurringTemplate>): Array<RecurringTemplate> {
    return value.map((x)=>from_candid_RecurringTemplate_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenseInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseInput): _ExpenseInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringTemplateInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringTemplateInput): _RecurringTemplateInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receiptUrl?: string;
    date: string;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}): {
    receiptUrl: [] | [string];
    date: string;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
} {
    return {
        receiptUrl: value.receiptUrl ? candid_some(value.receiptUrl) : candid_none(),
        date: value.date,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes?: string;
}): {
    name: string;
    dayOfMonth: bigint;
    amountCents: bigint;
    budgetId: bigint;
    notes: [] | [string];
} {
    return {
        name: value.name,
        dayOfMonth: value.dayOfMonth,
        amountCents: value.amountCents,
        budgetId: value.budgetId,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
